name: restaurant_app2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  http: ^1.2.0
  connectivity_plus: ^5.0.2
  lottie: ^3.0.0
  sqflite: ^2.3.2
  path: ^1.8.3
  flutter_local_notifications: ^16.3.2
  rxdart: ^0.27.7
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  android_alarm_manager_plus: ^3.0.4
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/restaurant.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: 'assets/restaurant.png'
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'assets/restaurant.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/restaurant.png'
